MODULES = jailed
include $(THEOS)/makefiles/common.mk

TWEAK_NAME = MyTweak
DISPLAY_NAME = LogStuff
BUNDLE_ID = com.myapp.LogStuff

ARCHS = arm64

MyTweak_FILES = *TargetTweakName.xm*
MyTweak_IPA = /Abs/Path/To/Target/app.ipa

MyTweak_USE_FISHHOOK=1
MyTweak_USE_CYCRIPT=0
MyTweak_USE_FLEX=0
MyTweak_USE_OVERLAY=0

include $(THEOS_MAKE_PATH)/tweak.mk
